name: CI
on: push
jobs:
  test:
    defaults:
      run:
        working-directory: app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Build and Test
      run: sbt -v +test
    - name: Archive reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: build/reports

