name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lean Stuff
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: ./HockiKlockiLean
